# Generated by Django 6.0.6 on 2026-07-07 03:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModeloEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(default='LAPTOP', max_length=100)),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=150)),
                ('tamano', models.CharField(max_length=20, verbose_name='Tamaño')),
                ('generacion', models.CharField(blank=True, max_length=50, null=True)),
                ('procesador', models.CharField(blank=True, max_length=50, null=True)),
                ('velocidad', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Modelo de Equipo',
                'verbose_name_plural': 'Catálogo de Modelos',
                'db_table': 'modelos_equipos',
                'unique_together': {('marca', 'modelo', 'procesador', 'velocidad')},
            },
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_serie', models.CharField(max_length=100, unique=True)),
                ('fecha_ingreso', models.DateField()),
                ('n_guia_ingreso', models.CharField(blank=True, max_length=50, null=True)),
                ('historial', models.CharField(default='NORMAL', max_length=50)),
                ('estado_grado', models.CharField(choices=[('GRADO A', 'Grado A'), ('GRADO B', 'Grado B'), ('GRADO C', 'Grado C'), ('GRADO D', 'Grado D'), ('GRADO M', 'Grado M')], max_length=50)),
                ('lote', models.CharField(blank=True, max_length=100, null=True)),
                ('memoria_ram', models.IntegerField()),
                ('disco', models.CharField(max_length=100)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('en_stock', models.BooleanField(default=True)),
                ('modelo', models.ForeignKey(db_column='modelo_id', on_delete=django.db.models.deletion.RESTRICT, to='inventario.modeloequipo')),
            ],
            options={
                'verbose_name': 'Equipo Físico',
                'verbose_name_plural': 'Equipos en Stock',
                'db_table': 'equipos',
            },
        ),
        migrations.CreateModel(
            name='Salida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_salida', models.DateField()),
                ('cliente', models.CharField(max_length=200)),
                ('n_guia_salida', models.CharField(max_length=50)),
                ('ram_salida', models.IntegerField(blank=True, null=True)),
                ('disco_salida', models.CharField(blank=True, max_length=100, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('equipo', models.OneToOneField(db_column='equipo_id', on_delete=django.db.models.deletion.RESTRICT, to='inventario.equipo')),
            ],
            options={
                'verbose_name': 'Registro de Salida',
                'verbose_name_plural': 'Salidas / Despachos',
                'db_table': 'salidas',
            },
        ),
    ]
