# Generated by Django 6.0.6 on 2026-07-11 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='disco',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='estado_grado',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='historial',
            field=models.CharField(default='NOMINAL', max_length=100),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='memoria_ram',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='modelo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.modeloequipo'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='n_guia_ingreso',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='modeloequipo',
            name='producto',
            field=models.CharField(choices=[('LAPTOP', 'Laptop'), ('CPU', 'CPU / Computadora'), ('AIO', 'All-in-One'), ('MONITOR', 'Monitor')], default='LAPTOP', max_length=50),
        ),
    ]
