# Generated by Django 6.0.6 on 2026-07-11 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_alter_equipo_disco_alter_equipo_estado_grado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modeloequipo',
            name='tamano',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Tamaño'),
        ),
    ]
